#!/usr/bin/env python3
"""Generate JourneyClassGuides.lua -- starter gear guides for the 8 non-rogue
classes, derived from the dataset (rogue stays hand-curated in JourneyRogueData).

Per class we keep class-usable, uncommon+ equippables and take the best few by
item level per slot per 10-level band. The in-game guide then score-filters
these by the player's spec weights, so spec-appropriateness is enforced at
display time -- this just provides a good candidate set per class.

Run from the project root:  python Tools/build_class_guides.py
"""
import json, collections

RAW = "Tools/_items_raw.json"
OUT = "JourneyClassGuides.lua"

QRANK = {"Common": 1, "Uncommon": 2, "Rare": 3, "Epic": 4, "Legendary": 5}
ARMOR_SUB = {"Cloth": 1, "Leather": 2, "Mail": 3, "Plate": 4}
TWO_HAND = {"Two-Hand"}
BODY = {"Head", "Shoulder", "Chest", "Wrist", "Hands", "Waist", "Legs", "Feet"}
NEUTRAL_SLOTS = {"Neck", "Finger", "Trinket", "Back", "Held In Off-hand"}
SHIELD_CLASSES = {"WARRIOR", "PALADIN", "SHAMAN"}

# Mirror Engine.WEAPON_PROF / CLASS_ARMOR (rogue omitted -- hand-curated).
WEAPON_PROF = {
    "WARRIOR": {0, 1, 4, 5, 6, 7, 8, 10, 13, 15, 2, 3, 18, 16},
    "PALADIN": {0, 1, 4, 5, 6, 7, 8},
    "HUNTER":  {0, 1, 6, 7, 8, 10, 13, 15, 2, 3, 18, 16},
    "PRIEST":  {4, 10, 15, 19},
    "SHAMAN":  {0, 1, 4, 5, 10, 13, 15},
    "MAGE":    {7, 10, 15, 19},
    "WARLOCK": {7, 10, 15, 19},
    "DRUID":   {4, 5, 6, 10, 13, 15},
}
CLASS_ARMOR = {
    "WARRIOR": {"Mail", "Plate"}, "PALADIN": {"Mail", "Plate"},
    "HUNTER": {"Leather", "Mail"}, "SHAMAN": {"Leather", "Mail"},
    "DRUID": {"Leather"}, "MAGE": {"Cloth"}, "PRIEST": {"Cloth"}, "WARLOCK": {"Cloth"},
}
PER_SLOT_BAND = 2  # keep the best N per slot per 10-level band


def band_index(req_level):
    """Mirror Engine.BandIndex: 1-10->1 ... 51-59->6, level 60 its own band 7.
    Must match the in-game split, else best-by-item-level buckets 51-60 together
    and the level-60 raid pieces starve the 51-59 band."""
    r = req_level or 1
    if r < 1:
        r = 1
    if r >= 60:
        return 7
    idx = (r - 1) // 10 + 1
    return 1 if idx < 1 else (6 if idx > 6 else idx)


def weapon_sub(sub, slot):
    two = slot in TWO_HAND
    return {"Axe": (1 if two else 0), "Mace": (5 if two else 4), "Sword": (8 if two else 7),
            "Polearm": 6, "Staff": 10, "Dagger": 15, "Fist Weapon": 13,
            "Bow": 2, "Crossbow": 18, "Gun": 3, "Thrown": 16, "Wand": 19}.get(sub)


def usable(cls, it):
    slot = it.get("slot")
    sub = it.get("subclass")
    if it["class"] == "Weapon":
        return weapon_sub(sub, slot) in WEAPON_PROF[cls]
    # Armor
    if sub == "Shield":
        return cls in SHIELD_CLASSES
    if slot in BODY:
        return sub in CLASS_ARMOR[cls]
    if slot in NEUTRAL_SLOTS:
        return True   # rings/necks/trinkets/cloaks are neutral
    return False      # relics/idols/etc -- skip for the starter guide


def main():
    data = json.load(open(RAW, encoding="utf-8"))
    eq = [it for it in data if it.get("class") in ("Weapon", "Armor")
          and it.get("name") and it.get("itemId") and it["itemId"] < 24284  # Vanilla/Era only
          and QRANK.get(it.get("quality"), 0) >= 2
          and 1 <= (it.get("requiredLevel") or 0) <= 60
          and "[" not in it["name"] and "XXXX" not in it["name"]]

    guides = {}
    for cls in WEAPON_PROF:
        buckets = collections.defaultdict(list)  # (slot, band) -> items
        for it in eq:
            if not usable(cls, it):
                continue
            band = band_index(it.get("requiredLevel"))
            buckets[(it.get("slot"), band)].append(it)
        picked, seen = [], set()
        for key, items in buckets.items():
            items.sort(key=lambda x: (-(x.get("itemLevel") or 0), x["itemId"]))
            for it in items[:PER_SLOT_BAND]:
                if it["itemId"] not in seen:
                    seen.add(it["itemId"])
                    picked.append(it)
        picked.sort(key=lambda x: (x.get("requiredLevel") or 0, x["itemId"]))
        guides[cls] = picked

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("-- AUTO-GENERATED by Tools/build_class_guides.py -- DO NOT EDIT BY HAND.\n")
        f.write("-- Starter class gear guides (rogue is hand-curated in JourneyRogueData).\n")
        f.write("-- Class-usable, uncommon+, best-by-item-level per slot per band; the\n")
        f.write("-- in-game guide score-filters these by spec. Regenerate: python Tools/build_class_guides.py\n\n")
        f.write("GearJourney_ClassGuides = GearJourney_ClassGuides or {}\n\n")
        for cls in sorted(guides):
            f.write('GearJourney_ClassGuides["%s"] = {\n' % cls)
            for it in guides[cls]:
                f.write('  {id=%d,name="%s"},\n' % (it["itemId"], it["name"].replace('\\', '\\\\').replace('"', '\\"')))
            f.write("}\n\n")
        total = sum(len(v) for v in guides.values())
    print("wrote", OUT, "-", {c: len(v) for c, v in guides.items()}, "total", total)


if __name__ == "__main__":
    main()
