#!/usr/bin/env python3
"""Build JourneyItemIndex.lua -- an exhaustive index of every equippable
weapon/armor in Classic, used by the Browse "Search all weapons & armor" box so
no real item is missing.

Source: nexus-devs/wow-classic-items data.json (itemIDs + names are game facts;
resolved/displayed by the client, consistent with HEALTH-3). We store a light
display row per item (no stats -- search lists items, scoring stays on the
curated pool). Run from the project root:

    python Tools/build_item_index.py
"""
import json, re

RAW = "Tools/_items_raw.json"
OUT = "JourneyItemIndex.lua"

QUALITY = {
    "Poor": "poor", "Common": "common", "Uncommon": "uncommon",
    "Rare": "rare", "Epic": "epic", "Legendary": "legendary",
    "Artifact": "legendary", "Heirloom": "rare",
}
SKIP_SLOTS = {"Shirt", "Tabard", "Non-equippable", "", None}
# True placeholders/test rows -- keep real items like "Old Greatsword".
JUNK = re.compile(r"\[|\]|^Monster\b|^OLD\b|\bTest Item\b|\(DEPRECATED\)|\(test\)|PH \[", re.I)


def lua_str(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    data = json.load(open(RAW, encoding="utf-8"))
    rows, seen = [], set()
    for it in data:
        if it.get("class") not in ("Weapon", "Armor"):
            continue
        slot = it.get("slot")
        if slot in SKIP_SLOTS:
            continue
        name = it.get("name")
        iid = it.get("itemId")
        if not name or not iid or iid in seen or JUNK.search(name):
            continue
        seen.add(iid)
        q = QUALITY.get(it.get("quality"), "common")
        icon = it.get("icon") or ""
        rows.append((iid, name, q, slot, it.get("requiredLevel") or 0, icon))

    rows.sort(key=lambda r: r[0])
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("-- AUTO-GENERATED by Tools/build_item_index.py -- DO NOT EDIT BY HAND.\n")
        f.write("-- Exhaustive index of equippable weapons/armor (Classic). itemIDs +\n")
        f.write("-- names are game facts; the client resolves the rest. Used by the\n")
        f.write("-- Browse 'Search all weapons & armor' box. Regenerate: python Tools/build_item_index.py\n\n")
        f.write("local Index = {\n")
        for iid, name, q, slot, rl, icon in rows:
            f.write('  {itemID=%d,name="%s",quality="%s",slot="%s",reqLevel=%d,icon="Interface\\\\Icons\\\\%s"},\n'
                    % (iid, lua_str(name), q, lua_str(slot), rl, lua_str(icon)))
        f.write("}\n\n")
        f.write("TitanJourney_ItemIndex = Index\nreturn Index\n")
    print("wrote", OUT, "with", len(rows), "items")


if __name__ == "__main__":
    main()
