#!/usr/bin/env python3
"""Build JourneyItemIndex.lua -- an exhaustive index of every equippable
weapon/armor in Classic, used by the Browse "Search all weapons & armor" box so
no real item is missing.

Source: nexus-devs/wow-classic-items data.json (itemIDs + names are game facts;
resolved/displayed by the client, consistent with HEALTH-3). We store a light
display row per item (no stats -- search lists items, scoring stays on the
curated pool). Run from the project root:

    python Tools/build_item_index.py
"""
import json, re

RAW = "Tools/_items_raw.json"
OUT = "JourneyItemIndex.lua"

QUALITY = {
    "Poor": "poor", "Common": "common", "Uncommon": "uncommon",
    "Rare": "rare", "Epic": "epic", "Legendary": "legendary",
    "Artifact": "legendary", "Heirloom": "rare",
}
SKIP_SLOTS = {"Shirt", "Tabard", "Non-equippable", "", None}
TWO_HAND_SLOTS = {"Two-Hand"}
BODY_ARMOR_SLOTS = {"Head", "Shoulder", "Chest", "Wrist", "Hands", "Waist", "Legs", "Feet"}
ARMOR_SUB = {"Cloth": 1, "Leather": 2, "Mail": 3, "Plate": 4}
SOURCE_CAT = {  # dataset source.category -> coarse, displayable sourceType
    "Quest": "Quest", "Vendor": "Vendor",
    "Boss Drop": "Drop", "Rare Drop": "Drop", "Zone Drop": "Drop",
}
# PvP reward sets are bought from vendors, so the dataset tags them "Vendor".
# Reclassify rank/honor-named gear to "PvP" -- but only when it isn't a world
# drop (e.g. "Champion's Armor" is a Rare Drop, not the PvP Champion's set).
DROP_CATS = {"Boss Drop", "Rare Drop", "Zone Drop"}
PVP_PREFIX = re.compile(
    r"^(Private's|Corporal's|Sergeant's|Master Sergeant's|Sergeant Major's|Knight's|"
    r"Knight-Lieutenant's|Knight-Captain's|Knight-Champion's|Lieutenant Commander's|"
    r"Commander's|Marshal's|Field Marshal's|Grand Marshal's|Scout's|Grunt's|"
    r"Senior Sergeant's|First Sergeant's|Stone Guard's|Blood Guard's|Legionnaire's|"
    r"Centurion's|Champion's|Lieutenant General's|General's|Warlord's|High Warlord's|"
    r"Highlander's|Defiler's|Outrider's|Outrunner's)\s"
)


def weapon_subclass(sub, slot):
    """Our weapon subClassID (1H/2H distinguished by slot). None = neutral."""
    two = slot in TWO_HAND_SLOTS
    base = {
        "Axe": (1 if two else 0), "Mace": (5 if two else 4), "Sword": (8 if two else 7),
        "Polearm": 6, "Staff": 10, "Dagger": 15, "Fist Weapon": 13,
        "Bow": 2, "Crossbow": 18, "Gun": 3, "Thrown": 16, "Wand": 19,
    }
    return base.get(sub)  # Exotic / Miscellaneous / Fishing Pole -> None (neutral)
# True placeholders/test rows -- keep real items like "Old Greatsword".
JUNK = re.compile(
    r"\[|\]|XXXX|^QR\b|^Monster\b|^OLD\b|\bTest\b|\bDEPRECATED\b|\bUNUSED\b|"
    r"\bPH\b|\bTBD\b|\bQA\b|\bDND\b|^PvP\b",
    re.I,
)


def lua_str(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    data = json.load(open(RAW, encoding="utf-8"))
    rows, seen = [], set()
    for it in data:
        if it.get("class") not in ("Weapon", "Armor"):
            continue
        slot = it.get("slot")
        if slot in SKIP_SLOTS:
            continue
        name = it.get("name")
        iid = it.get("itemId")
        # Classic Era only: Vanilla IDs cap ~24283, AND no Vanilla item requires
        # level > 60 -- so reqLevel > 60 catches TBC items with Vanilla-range IDs
        # (e.g. Hand of Eternity, id 23556 reqLevel 70). 200000+ already excluded.
        if not name or not iid or iid >= 24284 or (it.get("requiredLevel") or 0) > 60 \
           or iid in seen or JUNK.search(name):
            continue
        seen.add(iid)
        q = QUALITY.get(it.get("quality"), "common")
        icon = it.get("icon") or ""
        sub = it.get("subclass")
        is_weapon = it.get("class") == "Weapon"
        # class/subclass + armorType so Engine.CanUse works on index items.
        if is_weapon:
            cid, sid, atype = 2, weapon_subclass(sub, slot), None
        else:
            cid = 4
            sid = 6 if sub == "Shield" else ARMOR_SUB.get(sub)  # else None (neutral)
            atype = ARMOR_SUB.get(sub) and sub if slot in BODY_ARMOR_SLOTS else None
        src, cat = None, None
        s = it.get("source")
        if isinstance(s, dict):
            cat = s.get("category")
            src = SOURCE_CAT.get(cat)
        # Rank/honor-named gear that isn't a world drop is PvP reward gear.
        if PVP_PREFIX.match(name) and cat not in DROP_CATS:
            src = "PvP"
        rows.append((iid, name, q, slot, it.get("requiredLevel") or 0, icon, cid, sid, atype, src))

    rows.sort(key=lambda r: r[0])
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("-- AUTO-GENERATED by Tools/build_item_index.py -- DO NOT EDIT BY HAND.\n")
        f.write("-- Exhaustive index of equippable weapons/armor (Classic). itemIDs +\n")
        f.write("-- names are game facts; the client resolves the rest. Used by the\n")
        f.write("-- Browse 'Search all weapons & armor' box. Regenerate: python Tools/build_item_index.py\n\n")
        f.write("local Index = {\n")
        for iid, name, q, slot, rl, icon, cid, sid, atype, src in rows:
            extra = ",itemClassID=%d" % cid
            if sid is not None:
                extra += ",itemSubClassID=%d" % sid
            if atype:
                extra += ',armorType="%s"' % atype
            if src:
                extra += ',sourceType="%s"' % src
            f.write('  {itemID=%d,name="%s",quality="%s",slot="%s",reqLevel=%d,icon="Interface\\\\Icons\\\\%s"%s},\n'
                    % (iid, lua_str(name), q, lua_str(slot), rl, lua_str(icon), extra))
        f.write("}\n\n")
        f.write("TitanJourney_ItemIndex = Index\nreturn Index\n")
    print("wrote", OUT, "with", len(rows), "items")


if __name__ == "__main__":
    main()
