-- One-time extractor: harvest itemIDs (+ source) from the Retail AtlasLoot
-- Enhanced (fork) data files into JourneyAtlasData_Retail.lua, so the addon needs
-- no runtime dependency on AtlasLoot. Thin config over the shared core
-- (Tools/atlasloot_harvest.lua); the Classic sibling is Tools/extract_atlasloot.lua.
--
-- Scope: current-season endgame GEAR from the expansion instance modules (TWW +
-- Midnight) -- dungeon/raid drops, tagged coarse "Dungeon" so the overlay source
-- filter works unchanged (the per-instance name is kept in `source`). The
-- Crafting/Factions/PvP modules are cross-expansion and consumable-heavy; adding
-- them needs a gear-class filter (via the Item table) -- a follow-up.
--
-- Run from the project root:  lua Tools/extract_atlasloot_retail.lua

local harvest = dofile("Tools/atlasloot_harvest.lua")

harvest({
  addonsPath  = "D:\\Games\\World of Warcraft\\_retail_\\Interface\\AddOns",
  gameVersion = 12,  -- ItemDB:Add(addonname, 12) on the Midnight line
  isRetail    = true,
  modules = {
    { dir = "AtlasLoot_TheWarWithin", sourceType = "Dungeon" },
    { dir = "AtlasLoot_Midnight",     sourceType = "Dungeon" },
  },
  outFile = "JourneyAtlasData_Retail.lua",
  header = {
    "-- AUTO-GENERATED by Tools/extract_atlasloot_retail.lua -- DO NOT EDIT BY HAND.",
    "-- itemIDs + drop source harvested from AtlasLoot Enhanced (fork, Retail: TWW +",
    "-- Midnight instance drops). Game facts (item X from source Y); enriched at",
    "-- runtime via GetItemInfo. Regenerate: lua Tools/extract_atlasloot_retail.lua",
  },
})
