-- One-time extractor: harvest itemIDs (+ source) from AtlasLootClassic's Vanilla
-- data files into JourneyAtlasData.lua, so the addon needs no runtime dependency
-- on AtlasLoot. Thin config over the shared core (Tools/atlasloot_harvest.lua);
-- the Retail sibling is Tools/extract_atlasloot_retail.lua.
--
-- Run from the project root:  lua Tools/extract_atlasloot.lua

local harvest = dofile("Tools/atlasloot_harvest.lua")

harvest({
  addonsPath  = "D:\\Games\\World of Warcraft\\_classic_era_\\Interface\\AddOns",
  gameVersion = 1,  -- pretend Vanilla so version gates pick Classic content
  modules = {
    { dir = "AtlasLootClassic_DungeonsAndRaids", sourceType = "Dungeon" },
    { dir = "AtlasLootClassic_Crafting",         sourceType = "Crafted" },
    { dir = "AtlasLootClassic_Factions",         sourceType = "Faction" },
    { dir = "AtlasLootClassic_PvP",              sourceType = "PvP" },
  },
  outFile = "JourneyAtlasData.lua",
  header = {
    "-- AUTO-GENERATED by Tools/extract_atlasloot.lua -- DO NOT EDIT BY HAND.",
    "-- itemIDs + drop source harvested from AtlasLootClassic (Vanilla). These are",
    "-- game facts (item X from source Y); enriched at runtime via GetItemInfo.",
    "-- Regenerate with: lua Tools/extract_atlasloot.lua",
  },
})
